---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Validating podman, and an introduction to pods
    - name: module-02   
      label: Introduction to Podman Pods
    - name: module-03
      label: Pods and pod networking
    - name: module-04
      label: Operationalizing Pods with kube
    - name: module-05
      label: Managing Pods with Systemd and Quadlet

tabs:
  - name: ">_ Terminal"
    port: 443
    path: /tty1
    user: root
    host: rhel
