---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: Validating podman, and an introduction to pods
    - name: module-02
      label: Pods and pod networking
    - name: module-03
      label: Operationalizing Pods with kube
    - name: module-04
      label: Managing Pods with Systemd and Quadlet

tabs:
  - name: terminal
    port: 443
    path: /wetty
