== Pod networking

Let’s run a container, that lets us get to a bash shell within our pod,
to show that the httpd service is in fact accessible, just not from
outside the pod.

[source,bash,subs="+macros,+attributes",role=execute]
----
podman run -it --pod my-pod --rm registry.access.redhat.com/ubi9/ubi
----

In this example, we’re running a container, interactively, insdie of our
pod. You should get to a bash prompt inside of a RHEL UBI container.

[source,text]
----
# podman run -it –pod my-pod –rm registry.access.redhat.com/ubi9/ubi
[root@my-pod /]#

----

This container doesn't run any services, but if we try to use curl on localhost, we'll see that in fact we get a response!

[source,bash,subs="+macros,+attributes",role=execute]
----
curl http://127.0.0.1
----

[source,text]
----
[root@my-pod /]# curl http://127.0.0.1

It works!

[root@my-pod /]#

----
You can exit that shell with

[source,bash,subs="+macros,+attributes",role=execute]
----
exit
----

[source,text]
----
[root@my-pod /]# exit
exit

root@rhel :~#
----


So let's re-create our pod, and make it listen on port 80.  Let's stop, and then delete our pod.

[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod stop my-pod && podman pod rm my-pod
----

Now let’s make a new pod, with a new httpd container, and have the pod
forward port 8080 to port 80 inside the pod.

[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod create --name my-networked-pod -p 8080:80
----

And then we’ll need a container to listen on port 80, but we don’t need
to tell the container to forward anything, that’s handled at the pod
level.

[source,bash,subs="+macros,+attributes",role=execute]
----
podman run -d --pod my-networked-pod --name my-networked-httpd httpd
----

Now, if we check `+podman pod ps+` and `+podman ps+` we’ll see that both
the pod container, and the container itself show the port 8080 forward,
even though we didnt specify that on the container.

[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod ps
----

[source,text]
----
# podman pod ps
POD ID       NAME             STATUS  CREATED         INFRA ID   # OF CONTAINERS 
63c4292d1879 my-networked-pod Running 19 seconds ago 74be17e394e6 2
----

[source,bash,subs="+macros,+attributes",role=execute]
----
podman ps
----

[source,text]
----
# podman ps

CONTAINER ID IMAGE                         COMMAND   CREATED        STATUS             PORTS               NAMES
74be17e394e6 localhost/podman-pause:4.0.2-1652984291 26 seconds ago Up 13 seconds ago 0.0.0.0:8080->80/tcp 63c4292d1879-infra
0d13004a35e7 docker.io/library/httpd:latest httpd-foreground 13 seconds ago Up 12 seconds ago 0.0.0.0:8080->80/tcp my-networked-httpd
----


And we should be able to test that with `curl` now.

[source,bash,subs="+macros,+attributes",role=execute]
----
curl http://127.0.0.1:8080
----

[source,text]
----
# curl http://127.0.0.1:8080

It works!
----
