== Operationalizing Pods with kube

Podman generate, and Podman play

Another great feature of pods is that you can generate a yaml definition of your pod, and use it to re-create your pod using `+podman generate+` and `+podman play+`.

Let's generate a definition for your newly networked pod.


.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman generate kube my-networked-pod > my-networked-pod.yaml
----

This command has no expected output.

Now, we can see what we generated

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
cat my-networked-pod.yaml
----

.Output
[source,text]
----
# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.2.2
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/my-networked-httpd: 24f973ef9cb0d9b0495c39e9460100142e9cddcddcc9d657fcfdc6a8eba40213
  creationTimestamp: "2025-03-07T20:03:31Z"
  labels:
    app: my-networked-pod
  name: my-networked-pod
spec:
  containers:
  - image: docker.io/library/httpd:latest
    name: my-networked-httpd
    ports:
    - containerPort: 80
      hostPort: 8080
----

Now, if we stop, and remove our pod.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod stop my-networked-pod && podman pod rm my-networked-pod
----

.Output
[source,text]
----
my-networked-pod
23ae565d483ae6b1ee9a2c3cefbf1505cd6f10e1d69c7083f7583444451145f0
----

We can re-create it easily with `+podman play+`.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman play kube my-networked-pod.yaml
----

NOTE: This feature of podman works on other items as well. For instance, you can define a volume and use `+podman generate+` to store the volume definition as a yaml file. Then, you can re-create it on another system using podman play.

.Output
[source,text]
----
Pod:
9fb1a35e42cc730f02a93cddd5be19c2a33f3097ff6888cbba74076d75efc8b5
Container:
7eadafc08d71e20e50796ede7e3e4e45eb14547aa6738cd4203e0d747dfd3747
----

Now, if we check on `+podman pod ps+` and `+podman ps+` we will see a new pod, and container within it.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod ps
----

.Output
[source,text]
----
POD ID        NAME              STATUS      CREATED        INFRA ID      # OF CONTAINERS
2f3d42d6cac7  my-networked-pod  Running     3 minutes ago  d9f73884ad91  2
----

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman ps
----

.Output
[source,text]
----
CONTAINER ID  IMAGE                                    COMMAND           CREATED        STATUS        PORTS                 NAMES
d9f73884ad91  localhost/podman-pause:4.4.1-1682527828                    3 minutes ago  Up 3 minutes  0.0.0.0:8080->80/tcp  2f3d42d6cac7-infra
f87d81a769a3  docker.io/library/httpd:latest           httpd-foreground  3 minutes ago  Up 3 minutes  0.0.0.0:8080->80/tcp  my-networked-pod-my-networked-httpd
----

Now, if you try your `+curl+` command from earlier, you should get your test site just as before. You can see how this is a great way to save the deployment information and re-deploy quickly.

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
curl http://127.0.0.1:8080
----

.Output
[source,text]
----
<html><body><h1>It works!</h1></body></html>
----

In the next step, we're going a little deeper into operationalizing your pod, with Quadlet.
Remove the existing pod

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod stop my-networked-pod && podman pod rm my-networked-pod
----

.Output
[source,text]
----
my-networked-pod
9fb1a35e42cc730f02a93cddd5be19c2a33f3097ff6888cbba74076d75efc8b5
----

.Command
[source,bash,subs="+macros,+attributes",role=execute]
----
podman pod ps
----

.Output
[source,text]
----
POD ID      NAME        STATUS      CREATED     INFRA ID    # OF CONTAINERS
----
